# -*- coding: utf-8 -*-
"""scripts/mcp_meili.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kzVmcSK6fiDEmElgUh1VMlQFS7Gn8W-
"""

# 让 Claude 通过命令行调用此脚本来调试搜索
import sys
import json
from meilisearch import Client

# 配置
MEILI_URL = "http://localhost:7700"
MEILI_KEY = "masterKey" # 对应 .env 配置

def inspect_index(index_name):
    client = Client(MEILI_URL, MEILI_KEY)
    try:
        index = client.index(index_name)
        stats = index.get_stats()
        docs = index.get_documents({'limit': 3})
        return {
            "stats": stats,
            "sample_docs": docs.results
        }
    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python mcp_meili.py <index_name>")
        sys.exit(1)

    result = inspect_index(sys.argv[1])
    print(json.dumps(result, indent=2, ensure_ascii=False))